name: BusLinkNative
options:
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: '5.0'
    IPHONEOS_DEPLOYMENT_TARGET: '17.0'
    TARGETED_DEVICE_FAMILY: '1'
targets:
  BusLinkNative:
    type: application
    platform: iOS
    sources:
      - Sources
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: studio.mikegyver.buslinknative
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: BusLink
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
